version: "3.9"
services:
  db:
    image: postgres:14
    container_name: fastapi-startup-kit-db-container
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    working_dir: /app
    ports:
      - "8000:8000"
    container_name: fastapi-startup-kit-web-container
    volumes:
      - .:/app
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  db_data: